name: dmasley
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72447
title: Dean Masley
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#282828'
    - '#fefffe'
    - '#616161'
    - '#c6917a'
    - '#bd3542'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
